### DISCUSSION TITLE
Auto instrumentation modifying bucket size

### DISCUSSION THREAD

**Discussion by mrblonde91** [open-telemetry/opentelemetry-java-instrumentation#10072] [Q&A] [answered]
Is there an environment variable to modify the bucket dimensions for the auto instrumentation? Spent a while trawling documentation but couldn't find anything so just wanted to see if there's something I'm missing.

**Comment by laurit** [comment, marked as answer]
Buckets can be configured with metrics views as described in https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator either using the configuration file or programmatically using an agent extension https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension

**Reply by mrblonde91** [reply]
Can confirm this worked, thanks very much for the help.

**Reply by tqi-raurora** [reply]
@mrblonde91 

Would you be so kind as to share how you got it working?

I've been trying to change the bucket boundaries on http_server_duration histogram

**Reply by mrblonde91** [reply]
```
- selector:
    instrument_name: my-instrument
    instrument_type: COUNTER
    instrument_unit: ms
    meter_name: my-meter
    meter_version: 1.0.0
    meter_schema_url: http://example.com
  view:
    name: new-instrument-name
    description: new-description
    aggregation: explicit_bucket_histogram
    aggregation_args:
      bucket_boundaries: [1.0, 2.0, 5.0]
    attribute_keys:
      - foo
      - bar
```

Pretty much the view approach that @laurit provided in her incubator link.

**Reply by tqi-raurora** [reply]
@mrblonde91 Thanks for your response, I got it to work!

Leaving here what worked for me, in case any other newcomer like me comes across this page:

- Download the source code for the incubator extension here: https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator
- Build the extension using gradle `gradle build`
- Create the `my-view.yml` for customization. Ex for customizing http_server_request_duration_bucket:
```
- selector:
    instrument_name: http.server.request.duration
    instrument_type: HISTOGRAM
  view:
    aggregation: explicit_bucket_histogram
    aggregation_args:
      bucket_boundaries: [0.125, 0.5, 2, 8]
    attribute_keys:
      - http.request.method
      - http.response.status_code
      - http.route
      - network.protocol.version
      - url.scheme
```

-Run the application: with extension and the .yml view:
```
java -javaagent:opentelemetry-javaagent.jar \
     -Dotel.javaagent.extensions=opentelemetry-sdk-extension-incubator-1.44.0-alpha-SNAPSHOT.jar \
     -Dotel.experimental.metrics.view-config=my-view.yaml \
     -jar myapp.jar
```
