### DISCUSSION TITLE
Custom metrics not found in Prometheus

### DISCUSSION THREAD

**Discussion by zenvzenv** [open-telemetry/opentelemetry-java-instrumentation#10136] [Q&A]
I'm trying to generate some metric data myself using the Metrics SDK, but I can't find my own metrics in Prometheus.
Below is the component version I am using
```text
opentelemetry-javaagent:1.32.0
springboot:3.0.6
opentelemetry-spring-boot-starter:1.32.0-alpha
```
docker-compose.yml
```yml
version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250:14250"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config-demo.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config-demo.yaml:/etc/otel-collector-config-demo.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
```
prometheus.yaml
```yml
scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 2s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
```
springboot MetricsConfiguration.java
```java
package src.main.java.org.example;

import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.api.metrics.LongCounter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class MetricsConfiguration {
    @Bean
    public OpenTelemetry openTelemetry(){
        return GlobalOpenTelemetry.get();
    }

    @Bean
    @ConditionalOnBean(OpenTelemetry.class)
    public LongCounter successCounter(@Autowired OpenTelemetry openTelemetry) {
        return openTelemetry.getMeter("test1")
                .counterBuilder("success_counter")
                .setDescription("success counter")
                .setUnit("times")
                .build();
    }

    @Bean
    @ConditionalOnBean(OpenTelemetry.class)
    public LongCounter failedCounter(@Autowired OpenTelemetry openTelemetry) {
        return openTelemetry.getMeter("test1")
                .counterBuilder("failed_counter")
                .setDescription("failed counter")
                .setUnit("times")
                .build();
    }
}
```
springboot MetricsController.java
```java
package src.main.java.org.example;

import io.opentelemetry.api.metrics.LongCounter;
import jakarta.annotation.Resource;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Random;

@RestController
public class MetricsController {
    private static final Random RANDOM = new Random(System.currentTimeMillis());
    @Resource
    private LongCounter successCounter;
    @Resource
    private LongCounter failedCounter;

    @GetMapping("/test1")
    public String test1() {
        if (RANDOM.nextBoolean()) {
            successCounter.add(1L);
            return Boolean.TRUE.toString();
        } else {
            failedCounter.add(1L);
            return Boolean.FALSE.toString();
        }
    }
}
```
I can't find `success_counter` and `failed_counter` in the prometheus.
