### DISCUSSION TITLE
Configuring Hostname with Java OpenTelemetry Agent: Seeking Guidance

### DISCUSSION THREAD

**Discussion by imanAzi** [open-telemetry/opentelemetry-java-instrumentation#11012] [Q&A]
Our application runs on ECS Fargate. We are using the Java OpenTelemetry Agent for instrumentation, which sends all logs and metrics to our OTEL collector sidecar. 

Our OTEL collector is configured with:
```
receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes:
    actions:
      - key: host.name
        action: update
        value: "host_name"

exporters:
  datadog/api:
    traces:
      span_name_as_resource_name: true
      trace_buffer: 500
    hostname: ${PROJECT}-${ENV}
    api:
      key: ${DD_API_KEY}
      site: ${DD_SITE} #datadoghq.com
    host_metadata:
      tags:
        - geo.country:be
        - "env:${ENV}"
        - "service.name:${PROJECT}-${ENV}"

service:
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [datadog/api]
```

Our Java agent is configured with:
```
ENV JAVA_OPTS_APPEND="-Djboss.as.management.blocking.timeout=7200 -javaagent:/opt/test/opentelemetry-javaagent.jar"
ENV OTEL_SERVICE_NAME=TEST
ENV OTEL_LOG_LEVEL=WARN
ENV OTEL_METRICS_EXPORTER=otlp
ENV OTEL_TRACES_EXPORTER=otlp
ENV KEYCLOAK_HOST=localhost:8080
ENTRYPOINT ["/opt/test-wrapper.sh"]
```

The issue is that the host_metadata tags provided under the exporters are not being applied to the logs coming from the Opentelemtry Java agent. 

This is because the Java agent is grabbing the hostname from ECS Fargate, for example: `ip-10-10-10-10.<region>.compute.internal` but the Datadog exporter will only set the host_metadata tags if the hostname matches ${PROJECT}-{ENV}

Question:
Since it's not possible to set a custom hostname on ECS Fargate, is there a way we can force the Opentelemtry agent to use a custom hostname?
