### DISCUSSION TITLE
How to add arbitrary attributes to the exported metrics

### DISCUSSION THREAD

**Discussion by WesselAtWork** [open-telemetry/opentelemetry-java-instrumentation#11220] [Q&A] [answered]
Currently, after collecting the otlp data, I have `http_client_request_duration_seconds_sum`, `http_client_request_duration_seconds_count` and `http_client_request_duration_seconds_bucket` metrics.

They seem to come with the with `server_address`, `job`, `http_request_method`, `http_response_status_code`, `network_protocol_version`, `server_port` labels.

I want to add the [`url.path`](https://opentelemetry.io/docs/specs/semconv/attributes-registry/url/) to the metrics being exported.

I can see the attribute in the traces.

But more generally, how do we export arbitrary attributes with the metrics?
> I might be wrong, this might need to be setup in my collector

**Comment by laurit** [comment, marked as answer]
> But more generally, how do we export arbitrary attributes with the metrics?

you don't

> I want to add the [url.path](https://opentelemetry.io/docs/specs/semconv/attributes-registry/url/) to the metrics being exported.

So you wish to add `url.path` to `http.client.request.duration` metric. This can be achieved configuring a metric view https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator either programmatically in an agent extension or using a configuration file. Agent limits the set of attributes added to metrics using advice in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/4dae82c715e8be5dd4c16ea815953f4215460551/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/semconv/http/HttpMetricsAdvice.java#L26 metric view can override that advice and change the set of attributes added to the metric.

**Reply by WesselAtWork** [reply]
Couldn't quite figure out what I was doing wrong

Tried to get a minimal test going with:
```
- selector:
    instrument_name: 'http_client_request_duration_seconds_sum'
  view:
    attribute_keys:
      - url.path
```
Tried it on my java application with `OTEL_EXPERIMENTAL_METRICS_VIEW_CONFIG=/path/to/file.yaml`

I think it's supposed to override all the attributes with the list (in this case `url.path`, I was planing on adding the rest later), but it didn't seem to do anything for me.

Should I build the incubator artifact and add it to the class path, or is it already included in the javaagent?
> If using [autoconfigure](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure) with this artifact on your classpath

**Reply by laurit** [reply]
The name of the instrument is `http.client.request.duration`. I don't think you should add apostrophes or double quotes around the name.

> Should I build the incubator artifact and add it to the class path, or is it already included in the javaagent?

It is included in the agent.

**Reply by WesselAtWork** [reply]
Awesome got it working (kinda)!

## `url.full` works!
```yaml
- selector:
    instrument_name: http.client.request.duration
  view:
    attribute_keys:
      - url.full
      - http.request.method
      - http.response.status_code
      - error.type
      - network.protocol.name
      - network.protocol.version
      - server.address
      - server.port
```
Gives me the `url.full` + all the original attributes advised:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/d1fff1dfae1e2c20cd0336b7059262158daea880/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/semconv/http/HttpMetricsAdvice.java#L33-L39

## `url.*` don't work

Sadly All the other `url.*` attributes don't work.
```yaml
- selector:
    instrument_name: http.client.request.duration
  view:
    attribute_keys:
      - url.full  #this is the only one that works
      - url.path
      - url.domain
      - url.extension
      - url.fragment
      - url.original
      - url.port
      - url.query
      - url.registered_domain
      - url.scheme
      - url.subdomain
      - url.top_level_domain
```

## Workaround

If your request contain query parameters or resource ids, it's going to cause a cardinality explosion. 
> Of course if it doesn't, it isn't a concern

The workaround is to setup the [`peer.service`](https://opentelemetry.io/docs/specs/semconv/attributes-registry/peer/) with [`OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING`](https://opentelemetry.io/docs/languages/java/automatic/configuration/#peer-service-name)

e.g. `OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING="127.0.0.1=test-service"`

then doing
```yaml
- selector:
    instrument_name: http.client.request.duration
  view:
    attribute_keys:
      # your other keys here
      - peer.service
```

## PS
I should probably mention what I needed this for exactly.
I wanted to get stats for my external integration services. These services are not in my control and expose no metrics/tracing/monitoring.
I couldn't use the `server.address` because they are all funnelled through the same gateway.
Ideally id like to use `url.path` to differentiate the services, I can use the `url.full` with regexes to figure it out, but I am afraid of the cardinality explosion. 
For me the workaround gives me what I need.
