### DISCUSSION TITLE
Auto-instrumentation with JMX Beans

### DISCUSSION THREAD

**Discussion by sarkisjad** [open-telemetry/opentelemetry-java-instrumentation#11346] [Q&A]
Hello, 
I am trying to implement auto-instrumentation using the [jmx-metrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/jmx-metrics/javaagent)
My aim is to emit a metric on a simple Java application for the gc metrics.
This is my rules file: 
```
rules:
  - bean: java.lang:name=*,type=GarbageCollector
    metricAttribute:
      generation: param(name)
    mapping:
      LastGcInfo.duration:
        metric: my.own.last.gc.duration
        desc: my desc
        type: gauge
        unit: ms
```
I am looking for a way to add the process pid as an attribute to the datapoint attributes (not the resource attributes) of `my.own.last.gc.duration`.
Is there a way to do that? 
I know that the PID attribute is present in the attributes of the bean java.lang.Runtime. Can we extract it from there maybe?
