### DISCUSSION TITLE
How to send custom metrics to the collector once per minute

### DISCUSSION THREAD

**Discussion by mitht** [open-telemetry/opentelemetry-java-instrumentation#11663] [Q&A]
The metric data for etem.machine.memory is only reported once each time the Java program starts; how can I make it report data once per minute instead? Did I use the wrong method?
Can I use scheduleAtFixedRate for this?

 public ScheduledFuture<?> scheduleAtFixedRate(Runnable command,
				long initialDelay,
				long period,
				TimeUnit unit);

This is my startup configuration.  OTEL_METRIC_EXPORT_INTERVAL=10000 configuration does not take effect
# opentelemetry-javaagent-1.33.1
# otelcol-contrib_0.97.0
  
-Dotel.javaagent.debug=true -javaagent:/Users/rht/code/opentelemetry-java-instrumentation/javaagent/build/libs/opentelemetry-javaagent-1.33.1.jar -Dotel.service.name=my-service-06 -Dotel.instrumentation.jdbc.enabled=true  

# environment variables  
OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4317;OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED=false;OTEL_METRIC_EXPORT_INTERVAL=10000 

```yaml
# otelcol-contrib configuration
receivers:
  otlp: 
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
processors:
  batch:
    timeout: 5s
    send_batch_size: 10000
exporters:
  prometheus:
    endpoint: "127.0.0.1:17890"
    send_timestamps: true
    metric_expiration: 5m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true
extensions:
  health_check:
  pprof:
  zpages:
service:
  extensions: [ health_check, pprof, zpages ]
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ prometheus ]
```

```java
/*
 * Copyright The OpenTelemetry Authors
 * SPDX-License-Identifier: Apache-2.0
 */

package io.opentelemetry.javaagent.instrumentation.ht.asynmetrics;

import com.google.auto.service.AutoService;
import com.sun.management.OperatingSystemMXBean;
import io.opentelemetry.api.GlobalOpenTelemetry;
import io.opentelemetry.api.common.AttributeKey;
import io.opentelemetry.api.common.Attributes;
import io.opentelemetry.api.metrics.Meter;
import io.opentelemetry.javaagent.extension.AgentListener;
import io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk;
import java.lang.management.ManagementFactory;
import java.lang.management.RuntimeMXBean;
import java.util.concurrent.atomic.AtomicBoolean;

@AutoService(AgentListener.class)
public class HtAsynMetricsInstaller implements AgentListener {
    public static final AtomicBoolean INSTALLED = new AtomicBoolean(false);
    private static final AttributeKey<String> TYPE = AttributeKey.stringKey("type");

    public static final OperatingSystemMXBean osmxb =
            (OperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean();
    @Override
    public void afterAgent(AutoConfiguredOpenTelemetrySdk autoConfiguredOpenTelemetrySdk) {
        if (INSTALLED.compareAndSet(false, true)) {
            registerMachineMemory();
        }
    }

    private static void registerMachineMemory() {
        Meter meter = GlobalOpenTelemetry.getMeter(HtAsynMetricsInstaller.class.getName());
        meter
                .upDownCounterBuilder("etem.machine.memory")
                .ofDoubles()
                .setDescription("etem machine metric")
                .setUnit("count")
                .buildWithCallback(
                        resultLongObserver -> {
                            double totalMemorySize = osmxb.getTotalPhysicalMemorySize();
                            double freePhysicalMemorySize = osmxb.getFreePhysicalMemorySize();
                            double usedMemory = totalMemorySize - freePhysicalMemorySize;
                            resultLongObserver.record(freePhysicalMemorySize, Attributes.of(TYPE, "free"));
                            resultLongObserver.record(usedMemory, Attributes.of(TYPE, "used"));
                        });
    }
}
```
