### DISCUSSION TITLE
Appender Instrumentation for Log4j2 not exporting logs to collector when packaged

### DISCUSSION THREAD

**Discussion by Dimagreg** [open-telemetry/opentelemetry-java-instrumentation#12159] [Q&A]
* Hi, i'm currently writing my own java library in maven that includes manual instrumentation for log4j2 appender to send logs to opentelemetry collector inside a docker. 
* When i run the library with a main class inside, the jar executes just right and logs are exported to collector, but if i try to use this jar in my other project and use the same main class the log4j2 logs are not exported and no errors appear even on debug mode. Consider the fact that other appender for logback works fine with same configuration and instrumentations for http5, okhttp, java http client and their spans are exported. 
* Im really confused because i use the same dependencies for both projects but the moment i package the library and install it in another maven project, log4j2 stops exporting logs.

pom.xml in java library
```xml
    <dependencies>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-log4j-appender-2.17</artifactId>
            <version>2.6.0-alpha</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
            <version>1.39.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
            <version>1.40.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk-logs</artifactId>
            <version>1.40.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-logging</artifactId>
            <version>1.38.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
            <version>1.39.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-slf4j-impl</artifactId>
            <version>2.17.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.17.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.17.1</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.semconv</groupId>
            <artifactId>opentelemetry-semconv</artifactId>
            <version>1.26.0-alpha</version>
        </dependency>
    </dependencies>
````
In the other project im using the dependency for this specific jar.

log4j2.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" packages="io.opentelemetry.instrumentation.log4j.appender.v2_17">
    <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
            <PatternLayout
                    pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
        </Console>
        <OpenTelemetry name="OpenTelemetryAppender"/>
    </Appenders>
    <Loggers>
        <Root level="debug">
            <AppenderRef ref="OpenTelemetryAppender"/>
            <AppenderRef ref="Console"/>
        </Root>
    </Loggers>
</Configuration>
```

Main.java
```java
public class Main {

    private static final Logger logger = LogManager.getLogger(Main.class);

    public static void main(String[] args) {

        OpenTelemetry openTelemetry = OpenTelemetryConfigurator.initOpenTelemetry();

        // OTL Appender to log4j2
        Log4j2Appender.install(openTelemetry);

        logger.info("System starting");
        logger.info("System scanning");
        logger.info("System scanning complete");
    }
}
```

docker-compose.yml
```yml
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"   # OTLP gRPC endpoint
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_LOGS_EXPORTER=otlp
    depends_on:
      - otel-collector
    ports:
      - "8080:8080"
```
