### DISCUSSION TITLE
Http request headers as span attributes

### DISCUSSION THREAD

**Discussion by gpcmol** [open-telemetry/opentelemetry-java-instrumentation#12298] [Q&A] [answered]
I'm still puzzled how to configure the autoinstrumentation such that my pre-configured headers appear as span attributes.
I've read the Q&A, documentation, but not able to get i right.

This is my configuration

Instrumentation:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
spec:
  exporter:
    endpoint: http://opentelemetry-collector.telemetry.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.8.0
    env:
      - name: OTEL_JAVAAGENT_DEBUG
        value: "true"
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_CAPTURE_REQUEST_HEADERS
        value: "x-business-user"
```

When performing this against the application, my client header (x-business-user) is not emitted:
`curl -H "x-business-user: molc" http://localhost:8081/api/car`

This is the application log:
`[otel.javaagent 2024-09-19 06:35:51:369 +0000] [http-nio-8081-exec-3] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'GET /api/car' : bf1910279b48069fbb5d9b976009b96b ff64b2ba1f41371a SERVER [tracer: io.opentelemetry.tomcat-10.0:2.8.0-alpha] AttributesMap{data={url.scheme=http, thread.name=http-nio-8081-exec-3, network.peer.port=37532, network.protocol.version=1.1, user_agent.original=curl/7.81.0, thread.id=56, http.response.status_code=200, server.port=8081, http.route=/api/car, http.request.method=GET, url.path=/api/car, network.peer.address=127.0.0.1, server.address=localhost, client.address=127.0.0.1}, capacity=128, totalAddedValues=14}`

Java 21
Spring 3.2.4

What am I missing?
