### DISCUSSION TITLE
I want the agent to only collect metrics.

### DISCUSSION THREAD

**Discussion by shinozakisatoshi11** [open-telemetry/opentelemetry-java-instrumentation#12815] [Q&A]
To achieve this with the Java agent, I am using the following configuration. To accomplish my goal, I set OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "false" and then enable only what is necessary by setting them to true. Is there a better way to do this, or are there any specific instrumentations that should definitely be enabled for collecting metrics?

Additionally, I would like to know how to find the appropriate instrumentation for my purpose.

```yaml
  OTEL_EXPORTER_PROMETHEUS_PORT: "8888"
  OTEL_METRICS_EXPORTER: prometheus

  OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "false"
  OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_ENABLED: "true"
  OTEL_INSTRUMENTATION_OSHI_ENABLED: "true"
  OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_JAVA17_ENABLED: "true"
  OTEL_INSTRUMENTATION_JAVAAGENT_EXTENSION_API_ENABLED: "true"
  GLOBAL_AUTOCONFIGURE_ENABLED_PROPERTY: "true"
```
