### DISCUSSION TITLE
I want to execute GlobalOpenTelemetry.get() on a Java Agent.

### DISCUSSION THREAD

**Discussion by shinozakisatoshi11** [open-telemetry/opentelemetry-java-instrumentation#13015] [Q&A]
Issues I'm facing: I tried executing GlobalOpenTelemetry.get() on a Java Agent, but it didn't work.

What I've tried: I attempted GlobalOpenTelemetry.get(), but it didn't work as expected. It ended up behaving as if it was setting up a Prometheus server.

What I suspect: I am taking the approach of disabling certain Java Agent features and adding the necessary ones. I suspect there might be an INSTRUMENTATION that should be enabled, but I am unsure which one it is.

```yaml
# default-false
OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "false"

# metrics
OTEL_METRICS_EXPORTER: prometheus
OTEL_EXPORTER_PROMETHEUS_PORT: "8888"

# enable
OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_ENABLED: "true"
OTEL_INSTRUMENTATION_OSHI_ENABLED: "true"
OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_JAVA17_ENABLED: "true"
```
