### DISCUSSION TITLE
default schedule  HTTP GET Jaeger request

### DISCUSSION THREAD

**Discussion by wesleyzup** [open-telemetry/opentelemetry-java-instrumentation#7971] [Q&A]
Hi,
I'm testing opentelemetry using Java 8 and springboot 2.7.2.

I would like to know what means the default HTTP GET tracing request as shown bellow?  
Because it's invoked many times and i didn't make any requests, and it's being called automatically.
![image](https://user-images.githubusercontent.com/37084537/222838053-68e1d638-dfb6-4fc4-9968-013ebc82a9e9.png)

Is there how to configure the frequency time that it's called. E.g: Using spring application properties?

Thank you

**Comment by laurit** [comment]
Look at the span details, there are attributes/tags that will give you more info. If you can't figure it out on your own provide a minimal application that reproduces your issue.

**Reply by wesleyzup** [reply]
Hello, I couldn't understand why HTTP GET operation from Jaeger is being called cyclically.
I created this repository with instructions to reproduce the problem.

https://github.com/wesleyzup/app_tracing_opentelemetry

Thank you

**Reply by mateuszrzeszutek** [reply]
Isn't that the healthcheck you defined in the docker compose file?
```yaml
    healthcheck:
      test: curl http://localhost:8080
      interval: 5s
      retries: 10
      start_period: 5s
      timeout: 10s
```
