### DISCUSSION TITLE
Writing a LastGcInfo.memoryUsageBeforeGc in auto-instrumentation with JMX

### DISCUSSION THREAD

**Discussion by sarkisjad** [open-telemetry/opentelemetry-java-instrumentation#9391] [Q&A]
I am trying to implement auto-instrumentation using JMX on a simple Java application. As I am following the [documentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/jmx-metrics/javaagent), I am able to write to a Rules file beans.
There is however, a bean I'm unable to emit a metric for: `Garbage Collector – LastGcInfo.memoryUsageBeforeGc`. It is also the case for `memoryUsageAfterGc`.

Here is what I write in the Rules file: 

```
rules:
  - bean: java.lang:name=G1 Young Generation,type=GarbageCollector
    mapping:
      LastGcInfo.memoryUsageBeforeGc:
        metric: my.own.last.gc.memory.usage
        unit: By
```

And here is the error I get:
`[otel.javaagent 2023-09-05 17:38:04:233 +0300] [pool-5-thread-1] INFO io.opentelemetry.javaagent.shaded.instrumentation.jmx.engine.BeanAttributeExtractor - Unusable value javax.management.openmbean.TabularDataSupport for attribute LastGcInfo.memoryUsageBeforeGc and ObjectName java.lang:name=G1 Young Generation,type=GarbageCollector`

I understand that `memoryUsageBeforeGc` is a structure of information stored inside a TabularType. 
My question is, how can I get those information in metrics through the Rules file? How should this bean be written if I want to extract the SimpleType `used` for instance?
