### ISSUE TITLE
WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180

### ISSUE THREAD

**Issue by lafer-fz** [open-telemetry/opentelemetry-java-instrumentation#10025]
### Describe the bug

The execution command is as follows:

```
java -javaagent:/Users/liangfeng/tool/otel/opentelemetry-javaagent.jar \
     -Dotel.resource.attributes=service.name=ifc-newbee_ifc-label-data-webapp \
     -Dotel.exporter.otlp.endpoint=http://100.116.21.98:4317 \
     -Dotel.javaagent.debug=true \
     -jar ifc-label-data-webapp-1.0.0-SNAPSHOT.jar
```

The error message is as follows:

```
[otel.javaagent 2023-12-07 16:40:47:462 +0800] [OkHttp http://100.116.21.98:4317/...] DEBUG io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter failed
[otel.javaagent 2023-12-07 16:41:47:501 +0800] [OkHttp http://100.116.21.98:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180
[otel.javaagent 2023-12-07 16:41:47:501 +0800] [OkHttp http://100.116.21.98:4317/...] DEBUG io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter failed
[otel.javaagent 2023-12-07 16:42:47:521 +0800] [OkHttp http://100.116.21.98:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: 
[otel.javaagent 2023-12-07 16:42:47:522 +0800] [OkHttp http://100.116.21.98:4317/...] DEBUG io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter failed
[otel.javaagent 2023-12-07 16:43:47:523 +0800] [OkHttp http://100.116.21.98:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export metrics. Server responded with gRPC status code 2. Error message: Broken pipe (Write failed)
[otel.javaagent 2023-12-07 16:43:47:525 +0800] [OkHttp http://100.116.21.98:4317/...] DEBUG io.opentelemetry.sdk.metrics.export.PeriodicMetricReader - Exporter failed
```

### Steps to reproduce

My collecotr configuration：

```
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  prometheusremotewrite:
    endpoint: "http://victoriametrics:8428/api/v1/write"
    resource_to_telemetry_conversion:
      enabled: true

  logging:

  jaeger:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

  otlphttp:
    endpoint: http://100.116.2.223:10400

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, jaeger, otlphttp ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, prometheusremotewrite ]
```

### Expected behavior

Normal reporting

### Actual behavior

 Report an error

### Javaagent or library instrumentation version

v1.32.0

### Environment

**JDK**: JDK8
**OS**: 
**Spirng Boot**: v2.4.5
