### ISSUE TITLE
Can not collect trace of /js/j_security_check for WebSphere Liberty server using Java auto-instrumentation

### ISSUE THREAD

**Issue by xwgao** [open-telemetry/opentelemetry-java-instrumentation#10256]
### Describe the bug

I installed Community OpenTelemetry Operator 0.89.0 in my OpenShift 4.12.22 cluster. Created an OTEL collector and instrumentation and added annotation `instrumentation.opentelemetry.io/inject-java: "instrumentation"` into my deployment (the WebSphere Liberty server is running inside the pod container). But the OTEL collector can not get traces of endpoint `js/j_security_check` (the login page with form points to [j_security_check](https://www.ibm.com/support/pages/form-based-login-liberty)).

### Steps to reproduce

1. Installed Community OpenTelemetry Operator 0.89.0 in my OpenShift 4.12.22 cluster.
2. Created an OTEL collector as below.
```
spec:
  observability:
    metrics: {}
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:
        timeout: 10s
        send_batch_size: 10000
      metricstransform:
        transforms:
          - include: mas-core.duration
            match_type: regexp
            action: update
            operations:
              - action: update_label
                label: http.url
                new_label: url
              - action: update_label
                label: http.method
                new_label: method
              - action: update_label
                label: http.status_code
                new_label: code

    exporters:
      logging:
        verbosity: detailed
      prometheus:
        endpoint: "0.0.0.0:8889"
        send_timestamps: true
        metric_expiration: 1440m

    connectors:
      spanmetrics:
        namespace: mas-core
        histogram:
          unit: s
          explicit:
            buckets: [10ms, 100ms, 200ms, 400ms, 800ms, 1s, 1200ms, 1400ms, 1600ms, 1800ms, 2s, 4s, 6s, 8s, 10s]
        dimensions:
          - name: http.method
          - name: http.status_code
          - name: http.url
          - name: http.route
          - name: http.host

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [spanmetrics, logging]
        metrics:
          receivers: [spanmetrics]
          processors: [batch, metricstransform]
          exporters: [prometheus, logging]
  mode: statefulset
  resources: {}
  managementState: managed
  upgradeStrategy: automatic
  ingress:
    route: {}
  targetAllocator:
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  image: >-
    ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.89.0
  replicas: 1
```
3. Created an instrumentation as below.
```
spec:
  exporter:
    endpoint: 'http://otel-collector-headless:4317'
  java:
    env:
      - name: OTEL_INSTRUMENTATION_LIBERTY_ENABLED
        value: 'true'
      - name: OTEL_METRICS_EXPORTER
        value: none
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.31.0
    resources:
      limits:
        cpu: 500m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi
  sampler:
    argument: '1'
    type: parentbased_traceidratio
  go:
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.1.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
  nodejs:
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.44.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  resource: {}
  apacheHttpd:
    configPath: /usr/local/apache2/conf
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.3
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 128Mi
    version: '2.4'
  propagators:
    - tracecontext
    - baggage
    - b3
  dotnet:
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.1.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 128Mi
  nginx:
    configFile: /etc/nginx/nginx.conf
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.3
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 1m
        memory: 128Mi
  python:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: 'http://otel-collector-headless:4318'
      - name: OTEL_PYTHON_DISABLED_INSTRUMENTATIONS
        value: sqlite3
      - name: OTEL_PYTHON_LOG_CORRELATION
        value: 'true'
      - name: OTEL_PYTHON_LOG_LEVEL
        value: debug
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.41b0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 32Mi
      requests:
        cpu: 50m
        memory: 32Mi
```
4. Added annotation `instrumentation.opentelemetry.io/inject-java: "instrumentation"` into my deployment (the WebSphere Liberty server is running inside the pod container).
5. After the pod restarted, I checked the logs of the OTEL collector pod.
6. From the OTEL collector pod log, I found that it can not get the traces data for HTTP endpoint `js/j_security_check` (the login page with form points to j_security_check) when user login.

### Expected behavior

The OTEL collector can get traces of endpoint `js/j_security_check` (the login page with form points to j_security_check) for WebSphere Liberty server.

### Actual behavior

The OTEL collector can not get traces of endpoint `js/j_security_check` (the login page with form points to j_security_check) for WebSphere Liberty server.

### Javaagent or library instrumentation version

1.31.0

### Environment

**JDK**: 
java version "11.0.19" 2023-04-18
IBM Semeru Runtime Certified Edition 11.0.19.0 (build 11.0.19+7)
Eclipse OpenJ9 VM 11.0.19.0 (build openj9-0.38.0, JRE 11 Linux amd64-64-Bit Compressed References 20230519_626 (JIT enabled, AOT enabled)
OpenJ9   - d57d05932
OMR      - 855813495
JCL      - 61e8703a10 based on jdk-11.0.19+7)

**OS**: Red Hat Enterprise Linux 8.8
