### ISSUE TITLE
Vert.x Web 4.x HTTP/2 breaks when using the opentelemetry javaagent 

### ISSUE THREAD

**Issue by cbeneke** [open-telemetry/opentelemetry-java-instrumentation#10377]
### Describe the bug

We have two services running on K8s with Vert.X Web versions `4.4.6` and `4.3.8`, which we just started instrumenting with the opentelemetry-java-instrumentation in version `1.32.0` (also tested with `v2.0.0`). We are using the OTel Operator to inject the instrumentation:

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
spec:
  propagators:
  - tracecontext
  - baggage
  java:
    env:
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: service.namespace=$(POD_NAMESPACE),service.instance.id=$(OTEL_RESOURCE_ATTRIBUTES_POD_NAME)
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.32.0
[...]
```

into the pods. When connecting to any HTTP endpoint with HTTP/2 the connection gets established, gets upgraded and then breaks. Both using HTTP/1.1 and disabling the trace exporter result in the connections being correctly handled, but we can't find any hints what is going wrong in the javaagent debug logs, except a 

```
[otel.javaagent 2024-02-01 15:07:02:606 +0000] [vert.x-eventloop-thread-3] DEBUG io.opentelemetry.sdk.trace.SdkSpan - Calling updateName() on an ended Span.
```

Which we believe comes from the connection being terminated wrongly though (might not be the case).

At this point I'm unfortunately lost how to further debug the issue, and would appreciate any pointers.

### Steps to reproduce

Run a service with a Vert.x Web http client and enable auto-instrumentation with the opentelemetry-java-instrumentation. Then connect to the client with HTTP/2, e.g. with curl:

```
curl --http2 -vvv http://localhost:8080/
```

### Expected behavior

The client handles the HTTP request correctly.

### Actual behavior

The client disconnects after the HTTP/2 upgrade without any error message:

```
$ curl --http2 -vvv 'localhost:8080/api/v1/trades'
*   Trying [::1]:8080...
* Connected to localhost (::1) port 8080
> GET /api/v1/trades HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/8.4.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQAoAAAAAIAAAAA
>
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

pcap:

<img width="1399" alt="Screenshot 2024-02-01 at 19 20 01" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/222009/cd338844-0bfb-4583-94f9-7a48bc3fff26">

### Javaagent or library instrumentation version

v1.32.0, v2.0.0

### Environment

**JDK**: OpenJDK 17
**OS**: RockyLinux 9.1
