### ISSUE TITLE
SpringBoot Starter dependency and missing traces

### ISSUE THREAD

**Issue by aswarcewicz** [open-telemetry/opentelemetry-java-instrumentation#10401]
### Describe the bug

Not all traces have been logged in LoggingSpanExporter and not all traces have been forwarded to otel-collector.

### Steps to reproduce

1. Use spring-cloud-gateway in version 4.1.1
2. add dependency to io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter and optionally to io.opentelemetry.instrumentation:opentelemetry-spring-webflux-5.3:2.0.0-alpha
3. put in application.yaml:

```
otel:
  logs:
    exporter: otlp,logging
  traces:
    sampler: always_on
    exporter: otlp,logging
  metrics:
    exporter: otlp,logging
  service:
    name: gateway
  exporter:
    otlp:
      enabled: true
      endpoint: http://localhost:4317
      protocol: grpc
    logging:
      enabled: true
```
4. run app and try some random requests

### Expected behavior

all traces should appear in LoggingSpanExporter and all traces should be forwarded to otel-collector

### Actual behavior

only some traces are appearing in LoggingSpanExporter

### Javaagent or library instrumentation version

without agent, only spring dependencies

### Environment

**JDK**:
**OS**:
