### ISSUE TITLE
add ability to easily exclude health checks in spring starter

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#10527]
See https://cloud-native.slack.com/archives/C014L2KCTE3/p1707812808682639?thread_ts=1707739322.848999&cid=C014L2KCTE3

Proposal for `application.yaml`:

```yaml
otel:
  traces:
    sampler:
      experimental:
        routing:
          server:
            - attribute: http.route
              pattern: /actuator/
              sampler: always_off
            - attribute: http.route
              pattern: /get/cart
              sampler:
                name: traceidratio
                arg: 0.5
```
