### ISSUE TITLE
http duration seconds bucket boundray should be configrable 

### ISSUE THREAD

**Issue by lichenglin** [open-telemetry/opentelemetry-java-instrumentation#10793]
### Is your feature request related to a problem? Please describe.

Util now . the metric `http_server_request_duration_seconds_bucket` has several bucket boundray that delcared in  Java class 
 `io.opentelemetry.instrumentation.api.semconv.http.HttpMetricsAdvice` . 

`  static final List<Double> DURATION_SECONDS_BUCKETS =
      unmodifiableList(
          asList(0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0));
`

In some case , it should be modified to others.

### Describe the solution you'd like

it should be configrable by some settings .

for example  `otel.instrumentation.http.server.duration.seconds.bucket.boundray `

**Comment by laurit** [comment]
It is configurable via metrics views https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator

**Comment by chenglinli0** [comment]
> It is configurable via metrics views https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator

Do you mean declare a new metric instead of http_server_request_duration_seconds_bucket ? 

we hope it's totally generated by 'agent'  without any code.

**Comment by laurit** [comment]
> > It is configurable via metrics views https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator
> 
> Do you mean declare a new metric instead of http_server_request_duration_seconds_bucket ?
> 
> we hope it's totally generated by 'agent' without any code.

Please read https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator it describes how you can configure the bucket boundaries programmatically or with a configuration file. Using the configuration file does not involve any code.

**Comment by chenglinli0** [comment]
> > > It is configurable via metrics views https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator
> > 
> > 
> > Do you mean declare a new metric instead of http_server_request_duration_seconds_bucket ?
> > we hope it's totally generated by 'agent' without any code.
> 
> Please read https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator it describes how you can configure the bucket boundaries programmatically or with a configuration file. Using the configuration file does not involve any code.

Until now , the agent create metric `http_server_request_duration_seconds_bucket` .
 how can I change the bucket boundaries  by setting view.yaml?
I have tried  a lot but failed . If you can help , appreciate very much
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/113302886/a491efc9-0796-486e-918b-9f185e13dc9e)

**Comment by laurit** [comment]
@chenglinli0 could you share the view configuration you used.

**Comment by chenglinli0** [comment]
> @chenglinli0 could you share the view configuration you used.
@laurit , here it is.
```
- selector:
    instrument_name: my-instrument
    instrument_type: COUNTER
    instrument_unit: seconds
    meter_name: http_server_request_duration_seconds
    meter_version: 1.0.0
    meter_schema_url: http://example.com
  view:
    name: new-instrument-name
    description: new-description
    aggregation: explicit_bucket_histogram
    aggregation_args:
      bucket_boundaries: [1.0, 2.0, 8.0]
    attribute_keys:
      - foo
      - bar
  ```

**Comment by laurit** [comment]
try
```
- selector:
    instrument_name: http.server.request.duration
  view:
    aggregation: explicit_bucket_histogram
    aggregation_args:
      bucket_boundaries: [1.0, 2.0, 8.0]
```
