### ISSUE TITLE
opentelemetry-java-agent doesn't collect jvm metrics

### ISSUE THREAD

**Issue by fabjesus** [open-telemetry/opentelemetry-java-instrumentation#11183]
### Describe the bug

I'm facing an issue when trying to collect JVM metrics from Trino using the OpenTelemetry Collector Contrib and the OpenTelemetry Instrumentation Agent. I'm running the OpenTelemetry Java Instrumentation agent and configuring the collector contributed by OpenTelemetry to collect and export Trino's JVM metrics to Prometheus and I'm not able to see any metrics.

I would like to request assistance in understanding why my configuration rules are not being applied correctly for Trino's JVM metrics and how I can resolve this issue so that Trino's JVM metrics are collected and exported as expected.

Thanks in advance.

### Steps to reproduce

```
-javaagent:/path/to/opentelemetry-javaagent.jar -Dotel.jmx.config=/etc/trino/rules.yaml -Dotel.jmx.target.system=jvm -Dotel.javaagent.enabled=true
```

defined environment variables:
```
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=grpc
OTEL_LOGS_EXPORTER=none
OTEL_TRACES_EXPORTER=none
OTEL_METRICS_EXPORTER=otlp
OTEL_JAVAAGENT_DEBUG=true
```

rules.yaml
```
---
rules:
  - bean: trino.memory:name=general,type=memorypool
    mapping:
      freebytes:
        metric: otelcol_trino_memorypool_freebytes
        type: gauge
        desc: Pool memory freebytes
        unit: By
```

otel-collector:

```
receivers:
  otlp: #ingests OTLP formatted data from an app/system or another OTel collector
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics: # collects host metrics from the specified categories
    collection_interval: 1m
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:
      paging:

  # Collect own metrics
  prometheus: #ingests metrics in Prometheus format -- pre-configured to scrape the collector’s Prometheus endpoint
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["0.0.0.0:8888"]
processors:
  batch: # transmits telemetry data in batches, instead of streaming each data point or event.

exporters:
  prometheus:
    endpoint: "0.0.0.0:9275"
    namespace: otelcol
    send_timestamps: true
    enable_open_metrics: true

  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus, hostmetrics]
      processors: [batch]
      exporters: [logging, prometheus]

```

Call the prometheus endpoint of my OTEL collector.

### Expected behavior

Collect Trino's JVM metrics 

### Actual behavior

Trino's JVM metrics missing. For the configuration rule defined for mapping the attribute memorypool of bean `trino.memory:name=general,type=memorypool` to `otelcol_trino_memorypool_freebytes`. It doesn't work. I can't see the metrics `otelcol_trino_memorypool_freebytes` when calling the prometheus endpoint of my OTEL collector as below. 

### Javaagent or library instrumentation version

v2.3.0

### Environment

**JDK**: openjdk 11.0.22
**OS**: Debian 10

### Additional context

Using the JMX connector on Trino gives me the opportunity to query Java Management Extensions, and I can see the desired metric .

```
./trino-cli-436-executable.jar --server trino-otel.xpto.com:8080

trino> select * from jmx.current."trino.memory:name=general,type=memorypool";
 freebytes  |  maxbytes  | reservedbytes | reservedrevocablebytes |                 node                 |                object_name
------------+------------+---------------+------------------------+--------------------------------------+-------------------------------------------
 2727346112 | 2727346176 |            64 |                      0 | e48adfd0-14ca-5e7d-897e-9968b7ae72eb | trino.memory:type=MemoryPool,name=general
(1 row)
```

_No response_

**Comment by fabjesus** [comment]
```
./trino-cli-436-executable.jar --server trino-otel.xpto.com:8080

trino> select * from jmx.current."trino.memory:name=general,type=memorypool";
 freebytes  |  maxbytes  | reservedbytes | reservedrevocablebytes |                 node                 |                object_name
------------+------------+---------------+------------------------+--------------------------------------+-------------------------------------------
 2727346112 | 2727346176 |            64 |                      0 | e48adfd0-14ca-5e7d-897e-9968b7ae72eb | trino.memory:type=MemoryPool,name=general
(1 row)
```

**Comment by laurit** [comment]
Please provide instructions on how to run trino in a way that would allow connecting jconsole.

**Comment by laurit** [comment]
try
```
---
rules:
  - bean: trino.memory:name=general,type=MemoryPool
    mapping:
      FreeBytes:
        metric: otelcol_trino_memorypool_freebytes
        type: gauge
        desc: Pool memory freebytes
        unit: By
```
