### ISSUE TITLE
Trace data is being generated even though there are no request from service A to service B.

### ISSUE THREAD

**Issue by finda-yeongjo** [open-telemetry/opentelemetry-java-instrumentation#11348]
### Describe the bug

When monitoring Java applications using OpenTelemetry Java Auto-Instrumentation, the trace data incorrectly shows example service A calling service B ( A -> B), even though there is no actual call between A to B.  ( Based on the concept of microservices, A and B are producing and consuming data through a Kafka topic, so-called "loose coupling" between each other. )
This issue is evident in the traces_service_graph_request_total metric and the Zipkin trace data, which suggests a relationship that does not exist.

### Steps to reproduce

1. Deploy two Java services, A and B, in Kubernetes using the OpenTelemetry Java auto-instrumentation agent.

- image: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.29.0"
- name: OTEL_METRICS_EXEMPLAR_FILTER
        value: "trace_based"
 - name: OTEL_TRACES_EXPORTER
        value: "zipkin"
2. Observe the trace data in Tempo and the metrics in Prometheus.
3. Notice that the metrics and traces incorrectly indicate service A is making requests to service B.
4. You can check A->B in Grafana using the service graph or the traces_service_graph_request_total data.
5. Creating and testing a topic that they consume from each other would be more accurate.

### Expected behavior

The trace data and metrics should accurately reflect the interactions between services. Specifically, no traces or metrics should suggest a direct interaction between service A and service B when there is none.

### Actual behavior

The trace data and metrics incorrectly show interactions between service A and service B. Detailed trace inspection reveals only Redis existence checks from service B, unrelated to any direct request from service A. No overlapping headers, duplicated Trace IDs, or misconfigured headers are evident that could explain this anomaly.

### Javaagent or library instrumentation version

OpenTelemetry Java Auto-Instrumentation: v1.29.0, Java application: amazon corretto 17

### Environment

Service A
**JDK**: correto 17
**SPRING**: 2.7.1
**OS**: Amazon Linux (EKS)

----

Service B
**JDK**: correto 17
**SPRING**: 3.0.5
**OS**: Amazon Linux (EKS)

### Additional context

- All services are deployed as pods in EKS.
- The issue persists even after verifying that there are no overlapping or contaminated headers and that Trace IDs are unique and correctly configured.
- The environment configuration for OpenTelemetry instrumentation includes settings for exporting to Prometheus and Zipkin, capturing content-type headers for HTTP requests and responses.

**Comment by laurit** [comment]
Please provide a minimal sample app that reproduces the issue.

**Comment by serkan-ozal** [comment]
@laurit @finda-yeongjo 

As far as I understand the problem, I am not sure this is the problem of OTEL Java SDK/Agent, but Grafana and Zipkin. As far as I know, they are first grouping spans by trace id and creating service interactions by checking parent-child relation between spans. 

So in your case, since there is one PRODUCER span (let's say Span-1) from Service-A to Kafka and another CONSUMER span (let's say Span-2) from Kafka to Service-B, Grafana and Zipkin just interprets that Service-A interact with Service-B because Span-1 is the parent of Span-2. 

I agree with your statement that there is no such relation like Service-A => Service-B, but Service-A => Kafka, Kafka => Service-B, but I think, this is not OTEL Java SDK/Agent's issue, but Grafana and Zipkin.

**Comment by Cirilla-zmh** [comment]
@finda-yeongjo 
It seems that the metric `traces_service_graph_request_total` is generated by translating the interactions captured in the trace data. Hence, ensuring that the trace accurately records the call relationships is pivotal to your objectives.

If you wish to illustrate the call relationship of Service-A => Kafka => Service-B within your span, you might need to include the Kafka server in your tracing system. If the Kafka server is not capable to extract the tracing information within the message properties/headers and to export it correctly to the same observability data source, the role of Kafka cannot be accurately depicted.

**Comment by finda-yeongjo** [comment]
@laurit 
> Please provide a minimal sample app that reproduces the issue.

Given our customer-facing service environment dependency, I simply recommand two Java Spring applications just through a use some kafka topic. For reproduction purposes, deploy these applications in a "test" namespace. Additionally, deploy instrumentation in the same namespace, with the configuration provided below. Furthermore, otel-collector sends trace data to Tempo in our monitoring EKS cluster.

```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: test-instrumentation
  namespace: test
spec:
  propagators:
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  java:
    image: "ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.29.0"
    env:
      - name: OTEL_METRICS_EXPORTER
        value: "prometheus"
      - name: OTEL_METRICS_EXEMPLAR_FILTER
        value: "trace_based"
      - name: OTEL_TRACES_EXPORTER
        value: "zipkin"
      - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
        value: "http://{{ REPLACE_OTEL_COLLECTOR_SERVICE_ENDPOINT }}:9411/api/v2/spans"
      - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS
        value: "content-type"
      - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_RESPONSE_HEADERS
        value: "content-type"
```

---

@serkan-ozal 
Should I then take a look at Grafana and Zipkin? My instrumentation settings are as described above. Just in case, I tested it by adding these options:
```
      - name: OTEL_INSTRUMENTATION_MESSAGING_RECEIVE_TELEMETRY_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_MESSAGING_SEND_TELEMETRY_ENABLED
        value: "true"
```
As a result, there was no representation of Service A -> Service B, and it changed to "User" -> Service B. (User is not an example; it actually appears as the client value).
<img width="357" alt="스크린샷 2024-05-16 오전 11 40 48" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/136681927/16981e93-3768-4d81-bd5e-065b063a284d">

How can I fundamentally approach the problem?
