### ISSUE TITLE
Autoinstrument RabbitMQ

### ISSUE THREAD

**Issue by jdiegosierra** [open-telemetry/opentelemetry-java-instrumentation#11358]
### Describe the bug

Not sure if it's a bug or basically is not possible.

I'm trying to autoinstrument RabbitMQ in Kubernetes without using a collector.

### Steps to reproduce

I have both RabbitMQ and OpenTelemetry operators deployed. So first I deploy the Instrumentation:
```yaml
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: rabbitmq-cluster-sre-otel
  namespace: sre-testing-otel
spec:
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    image: open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.32.1 # I'm using a proxy
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: *****
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: "Authorization=Bearer *****"
      - name: OTEL_LOGS_EXPORTER
        value: otlp
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.name=<app-name>,service.version=<app-version>,deployment.environment=test
```
And then I deploy my RabbitMQ cluster:
```yaml
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster-sre-otel
  namespace: sre-testing-otel
  labels:
    app: rabbitmq-cluster-sre-otel
spec:
  image: rabbitmq:3.12.4-management # I'm using a proxy
  replicas: 1
  rabbitmq: 
    additionalPlugins:
      - rabbitmq_peer_discovery_k8s
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_top
      - rabbitmq_web_dispatch
      - rabbitmq_management
    additionalConfig:
      |
        log.console = true
        log.console.level = info
        log.console.formatter = json
  override:
    statefulSet:
      spec:
        template:
          metadata:
            labels:
              app: rabbitmq-cluster-sre-otel
            annotations:
              instrumentation.opentelemetry.io/inject-java: "true"
          spec:
            securityContext:
                fsGroup: 999
                runAsGroup: 999
                runAsUser: 999
            containers:
            - name: rabbitmq
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - CHOWN
                  - DAC_OVERRIDE
                  - FOWNER
                  - FSETID
                  - KILL
                  - MKNOD
                  - NET_RAW
                  - SETFCAP
                  - SETPCAP
                  - SETUID
                  - SETGID
                  - SYS_CHROOT
                privileged: false
              volumeMounts:
            volumes:
            initContainers:
            - name: setup-container
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - CHOWN
                  - DAC_OVERRIDE
                  - FOWNER
                  - FSETID
                  - KILL
                  - MKNOD
                  - NET_RAW
                  - SETFCAP
                  - SETPCAP
                  - SETUID
                  - SETGID
                  - SYS_CHROOT
                privileged: false
```

### Expected behavior

I expect to have my RabbitMQ cluster autoinstrumented and sending logs from the agent without a collector.

### Actual behavior

Logs are not being sent, and the logs of the RabbitMQ pod are:
```bash
Defaulted container "rabbitmq" out of: rabbitmq, setup-container (init), opentelemetry-auto-instrumentation-java (init)
2024-05-15 11:46:57.666029+00:00 [notice] <0.44.0> Application syslog exited with reason: stopped
2024-05-15 11:46:57.670042+00:00 [notice] <0.230.0> Logging: switching to configured handler(s); following messages may not be visible in this log output
# RabbitMQ logs
```

### Javaagent or library instrumentation version

opentelemetry-javaagent - version: 1.32.1

### Environment

**JDK**:
**OS**:
