### ISSUE TITLE
Logback OpenTelemetryAppender does not capture logger name as attribute

### ISSUE THREAD

**Issue by YuriyHolinko** [open-telemetry/opentelemetry-java-instrumentation#11670]
`OpenTelemetryAppender` does not allow us to enrich log records with logger name.

The only possible approach is to have the logger name attribute in log record is to use MDC, which is overhead imho.

We can add the functionality to the `OpenTelemetryAppender` to enrich log record with logger name attribute.

**Comment by jeanbisutti** [comment]
With the Logback OpenTelemetryAppender, you can have access to the logger name from the instrumentation scope of the log record.

**Comment by YuriyHolinko** [comment]
thanks for the attention, I will check and reply

**Comment by BenEfrati** [comment]
in your otel-collector yaml config you can add transform 
```
processors:
  transform/logs:
    log_statements:
      - context: scope
        statements:
          - set(attributes["log.logger"], name)
```
