### ISSUE TITLE
 Failed to export spans. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180

### ISSUE THREAD

**Issue by yanshicheng** [open-telemetry/opentelemetry-java-instrumentation#12096]
### Describe the bug

```bash
[otel.javaagent 2024-08-23 15:39:02:207 +0800] [http-nio-8008-exec-2] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'POST shop-app' : 1711f6c11591fc19566eaf09d301b088 5a707aed08736332 SERVER [tracer: io.opentelemetry.tomcat-10.0:2.7.0-alpha] AttributesMap{data={network.peer.port=56083, http.route=shop-app, http.request.method=POST, url.path=/shop-app/app/submit, error.type=503, server.address=127.0.0.1, client.address=127.0.0.1, network.peer.address=127.0.0.1, url.scheme=http, thread.name=http-nio-8008-exec-1, server.port=8008, network.protocol.version=1.1, http.response.status_code=503, user_agent.original=PostmanRuntime/7.41.1, thread.id=76}, capacity=128, totalAddedValues=15}
[otel.javaagent 2024-08-23 15:39:02:892 +0800] [OkHttp http://172.16.1.61:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180
[otel.javaagent 2024-08-23 15:39:02:893 +0800] [BatchSpanProcessor_WorkerThread-1] DEBUG io.opentelemetry.sdk.trace.export.BatchSpanProcessor - Exporter failed
```

### command
```bash
java -javaagent:../opentelemetry-javaagent.jar \
     -Dotel.service.name=shop-gateway \
     -Dotel.exporter.otlp.endpoint=http://172.16.1.61:4317 \
     -Dotel.exporter.otlp.protocol=grpc \
     -Dotel.traces.exporter=otlp \
     -Dotel.bsp.maxExportBatchSize=128 \
     -Dotel.bsp.scheduleDelayMillis=5000 \
     -Dotel.exporter.otlp.compression=gzip \
     -Dotel.exporter.otlp.timeout=30s \
     -Dotel.metrics.exporter=none \
     -Dotel.logs.exporter=none \
     -Dotel.resource.attributes=service.version=1.0,deployment.environment=production \
     -Dotel.javaagent.debug=true \
     -jar ./target/shop-gateway-1.0-SNAPSHOT.jar
```

### opentelemetry-collector config
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http: 
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - http://*
            - https://*
          allowed_headers:
            - Example-Header

exporters:
  logging:
    loglevel: info
  otlp:
    endpoint: 172.16.1.21:31696
    tls:
      insecure: true
    compression: gzip

processors:
  batch:
    send_batch_size: 5120
    timeout: 10s
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15
    spike_limit_mib: 800

service:
  telemetry:
    logs:
      level: info
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]
      processors: [batch, memory_limiter]
```

### Expected behavior

Trace data is written to the controller normally

### Actual behavior

 io.opentelemetry.sdk.trace.export.BatchSpanProcessor - Exporter failed

### Javaagent or library instrumentation version

 version: 2.7.0

### Environment

**JDK**: Java 17.0.11.
**OS**: mac
