### ISSUE TITLE
opentelemetry-spring-boot-starter MDC Instrumentation for logback not injecting trace id

### ISSUE THREAD

**Issue by Coupon-King** [open-telemetry/opentelemetry-java-instrumentation#13383]
### Describe the bug

When integrating opentelemetry-spring-boot-starter version 2.13.1 with Spring Boot 2.7.18, the traceId is not injected into the logs.

### Steps to reproduce

Providing the properties I'm using.
```
otel:
  logs:
    exporter: none
  metrics:
    exporter: none
  traces:
    exporter: none
  instrumentation:
    logback-mdc:
      enabled: true
```
The Properties of logback
`
<pattern>[%d{yyyy-MM-dd HH:mm:ss.SSS}%.-3d{Z}:00][%-5level][%mdc][%15.15thread] %40.40C{1} %-4L : [%m]%n</pattern>
`
In the output log, the content obtained by %mdc is empty.

### Expected behavior

In the printed log information, %mdc can obtain the information that contains traceid.

### Actual behavior

In the output log, the content obtained by %mdc is empty.

### Javaagent or library instrumentation version

opentelemetry-spring-boot-starter 2.13.1

### Environment

**JDK**: JDK17
