### ISSUE TITLE
JMX Metrics with yaml: need the ability to filter negative values

### ISSUE THREAD

**Issue by SylvainJuge** [open-telemetry/opentelemetry-java-instrumentation#13461]
For some metrics like `jvm.cpu.time` and `jvm.cpu.recent_utilization`, the JVM can return a negative value as the underlying data might not be available as indicated by [`OperatingSystemMXBean.getCpuLoad()` javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/jdk.management/com/sun/management/OperatingSystemMXBean.html#getCpuLoad()).

This corner case is properly handled in the runtime-telemetry implementation for JVM metrics as seen [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/dfe392e74103f9dcbc4715ab98efd98270ed7018/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/Cpu.java#L95-L98), but this is not the case for metrics that are defined in YAML, hence preventing to being 100% compliant with semconv for JVM metrics.

Also, the same issue is likely to happen with other systems for which metrics are captured through a yaml definition because returning a negative value is a common pattern to indicate something is not available.

This was discovered while working on https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/13392 where we try to capture JVM metrics that are compliant with [semantic conventions for java runtime](https://opentelemetry.io/docs/specs/semconv/runtime/jvm-metrics/).

Support for this could look like this in yaml:

```yaml
  - bean: java.lang:type=OperatingSystem
    prefix: jvm.
    mapping:
      # jvm.cpu.recent_utilization
      ProcessCpuLoad:
        metric: cpu.recent_utilization
        type: gauge
        unit: '1'
        discardNegativeValues: true
        desc: Recent CPU utilization for the process as reported by the JVM.
```

This is currently blocking progress on #13392
