### ISSUE TITLE
Toggle Support to Control Span Creation (Without Disabling Context Propagation)

### ISSUE THREAD

**Issue by radhakrishnan10192** [open-telemetry/opentelemetry-java-instrumentation#14007]
### Is your feature request related to a problem? Please describe.

**Description:**

In high-traffic applications, the volume of spans created by the OpenTelemetry Java Agent can become costly to process and manage, particularly for messaging instrumentations (e.g., Kafka producer and consumer spans), which tend to generate a large number of spans.

While disabling the instrumentation entirely (via `otel.instrumentation.[name].enabled=false`) is possible, this also breaks context propagation — which is undesirable, as we still want trace context to propagate downstream.

As of now, I do not see a clear option to disable or suppress span creation at the instrumentation level while preserving context propagation.

### Describe the solution you'd like

Introduce a per-instrumentation toggle such as: 
`otel.instrumentation.[instrumentation-name].experimental-span-suppression=true`

(or an equivalent officially supported mechanism) to:

- Suppress the creation of spans for a specific instrumentation (e.g., Kafka producer/consumer),
- While still allowing trace context propagation (i.e., injection and extraction of context continues).

**Comment by trask** [comment]
I think this will be possible once a few more things around enabling/disabling tracers by their instrumentation scope name

cc @jack-berg

**Comment by trask** [comment]
hi @radhakrishnan10192!

this is now possible using incubating API, e.g.

```
public class DisableKafkaSpansCustomizer implements AutoConfigurationCustomizerProvider {

  @Override
  public void customize(AutoConfigurationCustomizer autoConfiguration) {
    autoConfiguration.addTracerProviderCustomizer((tracerProviderBuilder, config) -> {
      SdkTracerProviderUtil.addTracerConfiguratorCondition(
          tracerProviderBuilder,
          ScopeConfiguratorBuilder.nameEquals("io.opentelemetry.kafka-clients-0.11"),
          TracerConfig.disabled()
      );
      return tracerProviderBuilder;
    });
  }
}
```

**Comment by trask** [comment]
ignore the above, even better, this is available in declarative config!

(see https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/javaagent#declarative-configuration for an example how to use declarative config)

```yaml
file_format: "1.0-rc.1"

tracer_provider:
  # Configure tracer behavior (experimental/development feature)
  tracer_configurator/development:
    # Configure specific tracers by name pattern
    tracers:
      # Disable standard Kafka clients instrumentation
      - name: io.opentelemetry.kafka-clients-0.11
        config:
          disabled: true
```
