### ISSUE TITLE
declarative configuration: `-` vs `_` in mapped properties

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#14133]
### Is your feature request related to a problem? Please describe.

Declarative configuration uses `_` instead of `-`.

- Properties: `otel.javaagent.add-thread-details`
- Declarative config: [attribute_value_length_limit: 4096](https://github.com/open-telemetry/opentelemetry-configuration/blob/c205770a956713e512eddb056570a99737e3383a/examples/kitchen-sink.yaml#L11)

### Describe the solution you'd like

Should we adapt DeclarativeConfigPropertiesBridge do make this tranlation?

**Comment by jack-berg** [comment]
> Should we adapt DeclarativeConfigPropertiesBridge do make this tranlation?

I wonder if have the bridge to both.. I.e. if you call `configProperties.getBoolean("otel.javaagent.add-thread-details")`, it would look for both:
```
instrumentation/development:
  java:
    javaagent:
      add-thread-details: true
```
Or:
```
instrumentation/development:
  java:
    javaagent:
      add_thread_details: true
```
And define a priority between them.
