### ISSUE TITLE
configure properties from spring application.yaml

### ISSUE THREAD

**Issue by lelvisl** [open-telemetry/opentelemetry-java-instrumentation#2390]
Hi!
I tried to configure via spring boot application.yml, like 
```yaml
server:
  port: 8081
  max-http-header-size: 40KB
...
otel:
  traces:
    sampler: always_on
    exporter: jaeger
  metrics:
    exporter: prometheus
  propagators: tracecontext,baggage,b3,jaeger,b3multi
  exporter:
    jaeger:
      endpoint: http://localhost:14250
  jaeger:
    service:
      name: tile-cache
  resource:
    attributes: service.name=tile-cache
```
looking at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md#jaeger-exporter

and, i failed. 

after, i understood, that javaagent don't know anything about my spring boot apllication on start (and properties from yaml). 

May be there any way to single file configuration of my application and this instrumentation?
