### ISSUE TITLE
Metrics updated every 60s only

### ISSUE THREAD

**Issue by devops-42** [open-telemetry/opentelemetry-java-instrumentation#6100]
Hi,

hope, I'm in the right project :)

I tried to setup the Java instrumentation of a SpringBoot app in connection with an OTel collector instance on K8s. 

My setup is:

```
[ SpringBoot-App + Instrumentation ] -> [otlp] -> [OpenTelemetry Collector] <- [prom] <- [Prometheus]
```

Within the springboot application I implemented a request counter for a REST endpoint. Everytime I make a call to the REST endpoint the counter raises by `1`.
When I query the metrics endpoint `/actuator/prometheus` of my app I see the counter immediately rising, but when querying the `/metrics` endpoint of the OpenTelemetry collector the value raises only after `60s`. 

Is there a possibility to lower that interval?

Thanks for your help!

**Comment by devops-42** [comment]
Hi @wallezhang ,

at first thanks for your fast response!
I tried to set this parameter as environment variable to the OpenTelemetry CRD:

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  labels:
    app.kubernetes.io/managed-by: opentelemetry-operator
  name: otel
  namespace: default
spec:
  config: 
    [...]
  env:
  - name: OTEL_METRIC_EXPORT_INTERVAL
    value: "5000"
  mode: deployment
  replicas: 1
  resources: {}
  targetAllocator: {}
  upgradeStrategy: automatic
status:
  version: 0.50.0
```

The operator created the pod with the specified environment variable, but the collector seems to ignore it: Metrics are still updated after 1 minute only.
Also tried to set the parameter `otel.metric.export.interval` in the `collector.yaml` which is mounted into the pod, but the collector pod throwed error messages due to the unknown config parameter and crashed.

Question: Where is the right place to set that option?

Thanks again for your help!
