### ISSUE TITLE
Opentelemetry auto instrumentation not working for java

### ISSUE THREAD

**Issue by mjrlgue** [open-telemetry/opentelemetry-java-instrumentation#7047]
**Describe the bug**
Hello, I followed this [tutorial ](https://medium.com/opentelemetry/using-opentelemetry-auto-instrumentation-agents-in-kubernetes-869ec0f42377) (thanks for the straightforward steps (y)), but the command `kubectl logs deployment.apps/otel-collector` doesn't print any trace, metric or logs. Instead I get that the exporters are started and waiting for data:
![image](https://user-images.githubusercontent.com/19733876/200041658-bd154894-dab0-4aee-9c00-5eb3fe2e2aed.png)

**Steps to reproduce**
1. applied the instrumentation:
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://otel-collector:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
  nodejs:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:latest
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
```
2. applied the petclinic app:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  namespace: otel
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
      annotations:
        sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
      - name: app
        image: ghcr.io/pavolloffay/spring-petclinic:latest
```

**What did you expect to see?**
expecting to see traces, metrics and logs when generating traffic

**What did you see instead?**
nothing, the receiver is waiting

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)

**Environment**
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**
- tested the above steps in `Microsoft Windows [version 10.0.19042.2130]` with docker desktop ` 4.11.1 (84025)` and got the same behavior! :/
- same thing for another java application tried to integrate OTel didn't work as well.
