### ISSUE TITLE
How can I add custom labels to the metrics that are produced by an auto-instrumented otel collector?

### ISSUE THREAD

**Issue by JustinPaulJohn** [open-telemetry/opentelemetry-java-instrumentation#7555]
I have a set of applications that are being auto-instrumented with a java otel agent/collector. The collector configuration for each application is as follows:
```
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ENDPOINT_HERE
      http:
        endpoint: ENDPOINT_HERE

exporters:
  awsxray:
    region: us-west-2
  otlp:
    endpoint: ENDPOINT_HERE

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
  
  extensions: [health_check]
```

Configuration is mostly default and collector metrics are being exposed on `localhost:8888/metrics`. A separate Prometheus server then looks at port 8888 to scrape the metrics. 

Metrics appear as follows:
```
# HELP otelcol_receiver_accepted_spans Number of spans successfully pushed into the pipeline` 
# TYPE otelcol_receiver_accepted_spans counter
otelcol_receiver_accepted_spans{receiver="otlp", service_instance_id="ID_HERE",service_version="latest",transport="grpc"} 
```

Is it possible to configure the collector's metrics so I can add the following to each?:
```
# HELP otelcol_receiver_accepted_spans Number of spans successfully pushed into the pipeline` 
# TYPE otelcol_receiver_accepted_spans counter
otelcol_receiver_accepted_spans{custom_label="custom_value", receiver="otlp", service_instance_id="ID_HERE",service_version="latest",transport="grpc"} 
```
