### ISSUE TITLE
opentelemetry-javaagent.jar does not read env variable - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT

### ISSUE THREAD

**Issue by hadson172** [open-telemetry/opentelemetry-java-instrumentation#7599]
**Describe the bug**
So i have an application - docker-compose based. There is a java aplication, frontend aplication and grafana agent to send logs to the grafana cloud. My backend docker compose looks like this

```
  backend-app:
    image: 'backend'
    build:
      context: ./../backend
    container_name: backend-app
    env_file:
      - ./.env
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://grafana-agent:4317
      OTEL_SERVICE_NAME: backend-app
      OTEL_TRACES_EXPORTER: otlp
    ports:
      - "127.0.0.1:8080:8080"
      ...
```

When i go the container and `echo $OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` getting correct result -> http://grafana-agent:4317
But logs on the containers are: 

```
[otel.javaagent 2023-01-17 19:43:29:183 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
[otel.javaagent 2023-01-17 19:44:29:184 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
[otel.javaagent 2023-01-17 19:45:29:187 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
[otel.javaagent 2023-01-17 19:46:29:182 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317
```

So it seems opentelemetry instead of  http://grafana-agent:4317 is trying to use default localhost. Any advices how do I fix this?

**What version are you using?**
[Version 1.21.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.21.0)

**Environment**
Compiler: AdoptOpenJDK 11.0.6
