### ISSUE TITLE
Missing http-traces - INVALID span context using kotlin coroutines

### ISSUE THREAD

**Issue by taskar82** [open-telemetry/opentelemetry-java-instrumentation#7756]
We have a issue with our Kotlin application that are using ktor coroutines. We are using automatic instrumentation with the latest Javaagent and the kotlin extension. We are using the OpenTelemetry operator for openshift. We have not added any code changes hoping the automatic agent will be enough. Correct or Wrong?

Followed this for adding the extension:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#build-and-add-extensions
And dowloaded the `opentelemetry-extension-kotlin-1.20.1.jar ` file.

When enabling DEBUG on the agent we can see "Invalid TraceId in B3 header: null'. Returning INVALID span context."

```
[otel.javaagent 2023-02-07 15:04:35:127 +0100] [OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10000 finished run in 45 ?s: OkHttp ConnectionPool
[otel.javaagent 2023-02-07 15:04:35:411 +0100] [eventLoopGroupProxy-3-1] DEBUG io.opentelemetry.extension.trace.propagation.B3PropagatorExtractorMultipleHeaders - Invalid TraceId in B3 header: null'. Returning INVALID span context.
[otel.javaagent 2023-02-07 15:04:38:874 +0100] [eventLoopGroupProxy-3-1] DEBUG io.opentelemetry.extension.trace.propagation.B3PropagatorExtractorMultipleHeaders - Invalid TraceId in B3 header: null'. Returning INVALID span context.
[otel.javaagent 2023-02-07 15:04:40:734 +0100] [eventLoopGroupProxy-3-1] DEBUG io.opentelemetry.extension.trace.propagation.B3PropagatorExtractorMultipleHeaders - Invalid TraceId in B3 header: null'. Returning INVALID span context.
[otel.javaagent 2023-02-07 15:04:40:737 +0100] [eventLoopGroupProxy-4-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'SELECT database_active.DUAL' : eb4cf6cbecf40f4506d6878ad25bacae 1cdc0ecb449d4c82 CLIENT [tracer: io.opentelemetry.jdbc:1.22.1-alpha] AttributesMap{data={thread.id=47, db.operation=SELECT, db.sql.table=DUAL, db.name=database_active, thread.name=eventLoopGroupProxy-4-1, db.user=username, db.connection_string=oracle:thin://testdb.internal.no:1521, net.peer.name=testdb.internal.no, net.peer.port=1521, db.system=oracle, db.statement=SELECT ? from DUAL}, capacity=128, totalAddedValues=11}
[otel.javaagent 2023-02-07 15:04:40:742 +0100] [eventLoopGroupProxy-3-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'HTTP GET' : eb4cf6cbecf40f4506d6878ad25bacae 6ac036829f227c25 SERVER [tracer: io.opentelemetry.netty-4.1:1.22.1-alpha] AttributesMap{data={thread.id=46, net.sock.peer.port=44588, http.scheme=http, http.method=GET, net.host.port=8080, http.response_content_length=888, http.user_agent=kube-probe/1.23, http.status_code=200, thread.name=eventLoopGroupProxy-3-1, net.transport=ip_tcp, net.host.name=10.130.9.126, http.flavor=1.1, http.target=/health, net.sock.peer.addr=10.130.8.1}, capacity=128, totalAddedValues=14}
[otel.javaagent 2023-02-07 15:04:41:047 +0100] [eventLoopGroupProxy-3-1] DEBUG io.opentelemetry.extension.trace.propagation.B3PropagatorExtractorMultipleHeaders - Invalid TraceId in B3 header: null'. Returning INVALID span context.
[otel.javaagent 2023-02-07 15:04:45:129 +0100] [OkHttp otel-collector-headless.openshift-operators] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10001 scheduled after 0 ?s: OkHttp otel-collector-headless.openshift-operators ping
[otel.javaagent 2023-02-07 15:04:45:129 +0100] [OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10001 starting : OkHttp otel-collector-headless.openshift-operators ping
[otel.javaagent 2023-02-07 15:04:45:129 +0100] [OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10001 finished run in 146 ?s: OkHttp otel-collector-headless.openshift-operators ping
[otel.javaagent 2023-02-07 15:04:45:129 +0100] [OkHttp http://otel-collector-headless.openshift-operators:4317/...] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10000 scheduled after 0 ?s: OkHttp ConnectionPool
[otel.javaagent 2023-02-07 15:04:45:130 +0100] [OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10000 starting : OkHttp ConnectionPool
[otel.javaagent 2023-02-07 15:04:45:130 +0100] [OkHttp ConnectionPool] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10000 run again after 300 s : OkHttp ConnectionPool
[otel.javaagent 2023-02-07 15:04:45:130 +0100] [OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10000 finished run in 102 ?s: OkHttp ConnectionPool
```

Added follwing Java option:
```
- name: JAVA_OPTS
              value: >-
                -Dotel.javaagent.extensions=/opentelemetry-extension-kotlin-1.20.1.jar
```

Instrumentation:
```
spec:
  dotnet:
    env:
      - name: OTEL_DOTNET_AUTO_TRACES_ENABLED_INSTRUMENTATIONS
        value: 'AspNet,HttpClient,SqlClient'
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:0.0.0
  exporter:
    endpoint: 'http://otel-collector-headless.openshift-operators:4317'
  java:
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: service.namespace=DEV-momento
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_JAVAAGENT_DEBUG
        value: 'true'
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.22.1
  nodejs:
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.34.0
  propagators:
    - tracecontext
    - baggage
    - b3
  python:
    image: >-
      ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.32b0
  resource: {}
  sampler:
    argument: '0.25'
    type: parentbased_traceidratio
```
Please advice
