### ISSUE TITLE
Wrong parent span while using Spring Cloud Gateway

### ISSUE THREAD

**Issue by 123liuziming** [open-telemetry/opentelemetry-java-instrumentation#9495]
### Describe the bug

When we use OpenTelemetry javaagent to instrument Spring Cloud Gateway(a microservice gateway based on Spring Webflux and Netty), we find that the parent span of HttpClient of Spring Cloud Gateway(a httpclient based on reactor-netty) is not the span of Spring Webflux.

The Spring Cloud Gateway handles HTTP request as follows:
Netty->Reactor Netty->Spring Webflux->Spring Cloud Gateway->Downstream Service

So we believe that the parent span of the span generated by the Spring Cloud Gateway's HttpClient should be the span generated by the Spring Webflux.

But the real trace is shown below:

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/32130965/90b61e8d-7b2b-466c-9c21-5e12eca435e4)

The span generated by Spring Cloud Gateway's HttpClient is as the same depth as the span generated by Spring Webflux

### Steps to reproduce

We just start a simple Spring Cloud Gateway application(version 3.0.0) with the following application.yml configuration file:
```
spring:
  cloud:
    gateway:
      response-timeout: ${RESPONSE_TIMEOUT:1s}
      routes:
        - id: httpbin
          uri: http://httpbin.org/
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1
```
And we use OpenTelemetry javaagent to instrument the related library:
```
-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5050
-Dotel.instrumentation.reactor-netty.connection-telemetry.enabled=true
-javaagent:~/opentelemetry-javaagent-1.28.0.jar
```
Then we just execute
```
curl localhost:8080/httpbin/get
```
We 've provided a minimized demo for you to reproduce the problem:
http://aliwei-food-picture.oss-cn-shenzhen.aliyuncs.com/A.zip

### Expected behavior

We expect that the span generated by Spring Webflux is the parent span of the span generated by Spring Cloud Gateway's HttpClient.

### Actual behavior

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/32130965/8c4a03c8-827a-4fd8-a368-a18883aa76c7)

The parent span of HttpClient of Spring Cloud Gateway(a httpclient based on reactor-netty) is not the span of Spring Webflux.

### Javaagent or library instrumentation version

v1.28.0

### Environment

**JDK**: openjdk version "1.8.0_352"
**OS**: macos
